version: "1.0"
dialect: sqlite
schema_dir: schema
migrations_dir: migrations
environments:
  development:
    database: myapp_dev.db
    timeout: 30
  staging:
    database: myapp_staging.db
    timeout: 30
  production:
    database: myapp_production.db
    timeout: 60
